knpu_oauth2_client:
  clients:
    facebook:
      type: facebook
      client_id: '%env(OAUTH_FACEBOOK_ID)%'
      client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
      redirect_route: admin_auth_facebook_process_login
      redirect_params: {}
      graph_api_version: v4.0

    linkedin:
      type: linkedin
      client_id: '%env(OAUTH_LINKEDIN_ID)%'
      client_secret: '%env(OAUTH_LINKEDIN_SECRET)%'
      redirect_route: admin_auth_linkedin_process_login
      redirect_params: {}